### ISSUE TITLE
Support for Laravel 7?

### ISSUE THREAD

**Issue by StephenGillCoop** [sebbmeyer/laravel-teams-connector#10]
@sebbmeyer any plans to make this compatible with Laravel 7? 

I've upgraded my app to Laravel 7.4 but had to remove this, because it wouldn't let me install.

**Comment by sebbmeyer** [comment]
@stevergill I updated the composer file (fc0bf443a31b224bbe35bb964f5f6832a99c36d4). Laravel 7 should now be supported with the lastest release (0.5.0)
