### ISSUE TITLE
Laravel 8 Support?

### ISSUE THREAD

**Issue by jagDanJu** [sebbmeyer/laravel-teams-connector#12]
@sebbmeyer Any plans to make this package compatible with Laravel 8?

Thanks!

**Comment by sebbmeyer** [comment]
@jagDanJu I will probably will take a look at it at the upcoming weekend. But feel free to submit a pull request.

**Comment by sebbmeyer** [comment]
added support for Laravel 8 (fe482d4df698fdc3cfca2debf4cc4a8f960b7387) in release 0.6.0
