### ISSUE TITLE
Support for Lumen

### ISSUE THREAD

**Issue by nenadvasic** [sebbmeyer/laravel-teams-connector#4]
Hey @sebbmeyer, did you consider to support Lumen framework? Lumen doesn't have the helper function config_path(), so an exception occurs with the following message:

> Call to undefined function Sebbmyr\\LaravelTeams\\config_path()

Quite a small change in the code is necessary to get this, so please let me know if you would like a PR.

Cheers 🍻

**Comment by sebbmeyer** [comment]
Hi @nenadvasic, I wasn't aware of this problem, that Lumen doesn't support config_path(). I would like a PR, sure.
