### ISSUE TITLE
Multiple Channels?

### ISSUE THREAD

**Issue by rpgwhore** [sebbmeyer/laravel-teams-connector#9]
Is there a way to instantiate a new Teams Connector for more than one channel?

**Comment by rpgwhore** [comment]
Closing Self Ticket

`$connector = new \Sebbmyr\Teams\TeamsConnector($webhook);

$card = New \Sebbmyr\LaravelTeams\Cards\CustomCard('Title'','Text');

$card->addColor('800080')
  ->addFacts('Details',[ 'Total Accounts' => number_format((int)$result['total']) ]);

$connector->send($card);`

**Comment by sebbmeyer** [comment]
@rpgwhore How did you solve your problem? Did you create multiple connectors and looped over them?

Having something like this could make it probably easier this kind of problems:

```php
$connector = new \Sebbmyr\Teams\TeamsConnector([$webhookA, $webhookB]);
```

then the connector would have to handle it on `$connector->send($card);`

**Comment by rpgwhore** [comment]
I mightve stated wrong in the multiple channels...

I was just trying to be able to use it on more than 1...

But i dont see anything wrong with looping over them if u want to do more
than one...
